spring:
  profiles:
    active: mariadb
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  batch:
    jdbc:
      initialize-schema: always

---

spring:
  config:
    activate:
      on-profile: h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/myplayground
    username: admin
    password:

---

spring:
  config:
    activate:
      on-profile: mariadb
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://maria-database.ciroumm1ym9r.ap-northeast-2.rds.amazonaws.com:3306/myplayground
    username: admin
    password: admin1234
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl